name:                mathematical-expressions-haskell
version:             0.1.0.0
github:              "githubuser/mathematical-expressions-haskell"
license:             BSD3
author:              "Timmy Jose"
maintainer:          "zoltan.jose@gmail.com"
copyright:           "2020 Timmy Jose"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mathematical-expressions-haskell/README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  mathematical-expressions-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mathematical-expressions-haskell

tests:
  mathematical-expressions-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mathematical-expressions-haskell
